## docker-compose up
## docker-compose exec $COMMAND
version: '2'
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./html:/usr/share/nginx/html"
      # - "./html/default.conf:/etc/nginx/conf.d/default.conf:ro"
